### ISSUE TITLE
不能跑起来

### ISSUE THREAD

**Issue by yangxing1** [AaronBank/react-native-style-adaptive#2]
ReferenceError: Can't find variable: pixelRatio

**Comment by yangxing1** [comment]
![image](https://user-images.githubusercontent.com/16661092/168722374-d1bff801-a95b-417a-a3af-c0f54a7d9eeb.png)

add import is ok

**Comment by KaneShen** [comment]
Thank you for your suggestion, I will modify it as soon as possible
